### ISSUE TITLE
No popups when an invalid input is submitted 

### ISSUE THREAD

**Issue by Effixion** [Eugenetanwl3881/MaybeStocks#49]
On the buy and sell page, if invalid inputs are submitted, like "e", "E", or "0", no popups appear to tell the user that they are unable to submit invalid inputs. Yet the website will allow the transaction to go through and it logs the submission as a transaction where the user bought 0 stocks. Additionally, no popups appear if the symbol field is left blank, which would confuse the user as to why the buttons are not doing anything when they click the buy/sell button.

**Comment by Eugenetanwl3881** [comment]
Ok fixed the bug with new additions of checks

**Comment by Effixion** [comment]
Yep checked that it was working when merging pull request #48.
